blog/config/routes.rb
Blog::Application.routes.draw do
  resources :commen

  resources :posts

end

blog/app/models/comman.rb
class Comman < ActiveRecord::Base
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/commen_controller.rb
class CommenController < ApplicationController
  before_action :set_comman, only: [:show, :edit, :update, :destroy]

  # GET /commen
  # GET /commen.json
  def index
    @commen = Comman.all
  end

  # GET /commen/1
  # GET /commen/1.json
  def show
  end

  # GET /commen/new
  def new
    @comman = Comman.new
  end

  # GET /commen/1/edit
  def edit
  end

  # POST /commen
  # POST /commen.json
  def create
    @comman = Comman.new(comman_params)

    respond_to do |format|
      if @comman.save
        format.html { redirect_to @comman, notice: 'Comman was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comman }
      else
        format.html { render action: 'new' }
        format.json { render json: @comman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commen/1
  # PATCH/PUT /commen/1.json
  def update
    respond_to do |format|
      if @comman.update(comman_params)
        format.html { redirect_to @comman, notice: 'Comman was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commen/1
  # DELETE /commen/1.json
  def destroy
    @comman.destroy
    respond_to do |format|
      format.html { redirect_to commen_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comman
      @comman = Comman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comman_params
      params.require(:comman).permit(:post_id, :\, :body)
    end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :\, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/commen_helper.rb
module CommenHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/commen/_form.html.erb
<%= form_for(@comman) do |f| %>
  <% if @comman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comman.errors.count, "error") %> prohibited this comman from being saved:</h2>

      <ul>
      <% @comman.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :\ %><br>
    <%= f.text_field :\ %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/commen/edit.html.erb
<h1>Editing comman</h1>

<%= render 'form' %>

<%= link_to 'Show', @comman %> |
<%= link_to 'Back', commen_path %>

blog/app/views/commen/index.html.erb
<h1>Listing commen</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>\</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commen.each do |comman| %>
      <tr>
        <td><%= comman.post_id %></td>
        <td><%= comman.\ %></td>
        <td><%= comman.body %></td>
        <td><%= link_to 'Show', comman %></td>
        <td><%= link_to 'Edit', edit_comman_path(comman) %></td>
        <td><%= link_to 'Destroy', comman, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comman', new_comman_path %>

blog/app/views/commen/new.html.erb
<h1>New comman</h1>

<%= render 'form' %>

<%= link_to 'Back', commen_path %>

blog/app/views/commen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comman.post_id %>
</p>

<p>
  <strong>\:</strong>
  <%= @comman.\ %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comman.body %>
</p>

<%= link_to 'Edit', edit_comman_path(@comman) %> |
<%= link_to 'Back', commen_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :\ %><br>
    <%= f.text_field :\ %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>\</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.\ %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>\:</strong>
  <%= @post.\ %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>